# Generated by Django 3.2.16 on 2023-05-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20230503_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'verbose_name': 'день рождения', 'verbose_name_plural': 'БД Дней Рождений'},
        ),
    ]
